### PR TITLE
demoA first commit

### PR DESCRIPTION
**Pull request by bhusan2662**
plz check demoA code

### CODE REVIEW

**Comment by bhusan2662** [comment]
Hi

**Comment by bhusan2662** [comment]
hi

**Comment by bommi2662** [comment]
hi plz merge code

**Comment by bhusan2662** [comment]
ok thank u sir

**Comment by bommi2662** [comment]
hi plz add controller to this project

**Comment by bommi2662** [comment]
plz merge

**Comment by bhusan2662** [comment]
hi

**Comment by bommi2662** [comment]
commit

**Pull request closed without merging**
